export const allDestinations = [
  // Indian Destinations
  {
    id: 'taj-mahal',
    name: 'Taj Mahal, Agra',
    country: 'India',
    category: 'Indian Heritage',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
    description: 'The iconic monument to love, one of the Seven Wonders of the World',
    price: 2499,
    rating: 4.9,
    reviews: 2345,
    duration: '3 days',
    activities: ['Heritage Tour', 'Photography', 'Cultural Experience'],
  },
  {
    id: 'goa-beaches',
    name: 'Goa',
    country: 'India',
    category: 'Beach Paradise',
    image: 'https://images.unsplash.com/photo-1537905904737-146510eee5cd?w=800&q=80',
    description: 'Tropical beaches, water sports, nightlife, and Portuguese architecture',
    price: 1999,
    rating: 4.7,
    reviews: 1856,
    duration: '5 days',
    activities: ['Beach', 'Water Sports', 'Nightlife', 'Food Tour'],
  },
  {
    id: 'kerala-backwaters',
    name: 'Kerala Backwaters',
    country: 'India',
    category: 'Nature & Lakes',
    image: 'https://images.unsplash.com/photo-1606216174052-e96768642f5b?w=800&q=80',
    description: 'Lush green landscapes, houseboat cruises, and tranquil backwaters',
    price: 2199,
    rating: 4.8,
    reviews: 1543,
    duration: '4 days',
    activities: ['Houseboat Cruise', 'Nature Walk', 'Ayurveda Spa', 'Local Food'],
  },
  {
    id: 'rajasthan-golden',
    name: 'Rajasthan Golden Triangle',
    country: 'India',
    category: 'Royal Heritage',
    image: 'https://images.unsplash.com/photo-1599934946891-90f1f3f9dd7f?w=800&q=80',
    description: 'Majestic forts, palaces, deserts, and vibrant culture',
    price: 2899,
    rating: 4.8,
    reviews: 1234,
    duration: '6 days',
    activities: ['Palace Tours', 'Desert Safari', 'Camel Ride', 'Cultural Shows'],
  },
  {
    id: 'ladakh-adventures',
    name: 'Ladakh',
    country: 'India',
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'High altitude mountains, Buddhist monasteries, and adventure activities',
    price: 3299,
    rating: 4.9,
    reviews: 876,
    duration: '7 days',
    activities: ['Trekking', 'Mountain Biking', 'Monastery Tours', 'Stargazing'],
  },
  {
    id: 'varanasi-spiritual',
    name: 'Varanasi',
    country: 'India',
    category: 'Spiritual',
    image: 'https://images.unsplash.com/photo-1597936212624-0ad8e4e8d83f?w=800&q=80',
    description: 'Sacred ghats, Ganga river ceremonies, and spiritual awakening',
    price: 1699,
    rating: 4.6,
    reviews: 945,
    duration: '3 days',
    activities: ['Ghat Tours', 'Boat Rides', 'Temple Visits', 'Yoga Sessions'],
  },
  {
    id: 'mumbai-gateway',
    name: 'Mumbai',
    country: 'India',
    category: 'Urban',
    image: 'https://images.unsplash.com/photo-1605471423112-d4d3b32b5ad3?w=800&q=80',
    description: 'Gateway to India, Bollywood city, beaches and modern culture',
    price: 1899,
    rating: 4.5,
    reviews: 1102,
    duration: '3 days',
    activities: ['City Tour', 'Beach Walk', 'Food Tour', 'Museum Visits'],
  },
  {
    id: 'shimla-himalayas',
    name: 'Shimla & Himalayas',
    country: 'India',
    category: 'Mountains',
    image: 'https://images.unsplash.com/photo-1626621674934-3e8adb14cb5e?w=800&q=80',
    description: 'Hill station charm, snow peaks, adventure sports',
    price: 2299,
    rating: 4.7,
    reviews: 876,
    duration: '4 days',
    activities: ['Hiking', 'Snow Sports', 'Mall Road Shopping', 'Adventure Sports'],
  },
  {
    id: 'khajuraho-temples',
    name: 'Khajuraho Temples',
    country: 'India',
    category: 'Heritage',
    image: 'https://images.unsplash.com/photo-1599934946891-90f1f3f9dd7f?w=800&q=80',
    description: 'Ancient temples with intricate carvings and architectural marvel',
    price: 1799,
    rating: 4.6,
    reviews: 567,
    duration: '2 days',
    activities: ['Temple Tours', 'Photography', 'Local Guides', 'Light Show'],
  },
  {
    id: 'jaipur-pink-city',
    name: 'Jaipur Pink City',
    country: 'India',
    category: 'Royal Heritage',
    image: 'https://images.unsplash.com/photo-1599934946891-90f1f3f9dd7f?w=800&q=80',
    description: 'Pink city charm, palaces, bazaars, and Hawa Mahal',
    price: 1699,
    rating: 4.7,
    reviews: 1234,
    duration: '3 days',
    activities: ['Palace Tour', 'Bazaar Shopping', 'Cooking Class', 'City Tour'],
  },

  // World Destinations
  {
    id: 'paris-romance',
    name: 'Paris',
    country: 'France',
    category: 'Romance',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    description: 'The City of Light with iconic landmarks and world-class cuisine',
    price: 3499,
    rating: 4.9,
    reviews: 5432,
    duration: '5 days',
    activities: ['Eiffel Tower', 'Museums', 'Seine Cruise', 'French Cuisine'],
  },
  {
    id: 'bali-tropical',
    name: 'Bali',
    country: 'Indonesia',
    category: 'Tropical Paradise',
    image: 'https://images.unsplash.com/photo-1542259009477-d625272157b7?w=800&q=80',
    description: 'Beaches, temples, rice terraces, and spiritual culture',
    price: 1799,
    rating: 4.8,
    reviews: 4123,
    duration: '5 days',
    activities: ['Beach', 'Temple Tours', 'Surfing', 'Yoga Retreat'],
  },
  {
    id: 'tokyo-modern',
    name: 'Tokyo',
    country: 'Japan',
    category: 'Urban Adventure',
    image: 'https://images.unsplash.com/photo-1540959375944-7049f642c555?w=800&q=80',
    description: 'Modern metropolis blending tradition and cutting-edge technology',
    price: 2999,
    rating: 4.8,
    reviews: 3456,
    duration: '4 days',
    activities: ['City Tour', 'Temple Visits', 'Food Tour', 'Shopping'],
  },
  {
    id: 'maldives-luxury',
    name: 'Maldives',
    country: 'Maldives',
    category: 'Luxury Beach',
    image: 'https://images.unsplash.com/photo-1611273426858-450d8e3c9fce?w=800&q=80',
    description: 'Overwater bungalows, crystal waters, and pristine coral reefs',
    price: 4999,
    rating: 4.9,
    reviews: 2876,
    duration: '5 days',
    activities: ['Snorkeling', 'Diving', 'Water Sports', 'Spa'],
  },
  {
    id: 'iceland-nature',
    name: 'Iceland',
    country: 'Iceland',
    category: 'Nature',
    image: 'https://images.unsplash.com/photo-1504681869696-d977e3a34c65?w=800&q=80',
    description: 'Glaciers, waterfalls, geysers, and northern lights',
    price: 3799,
    rating: 4.9,
    reviews: 2345,
    duration: '6 days',
    activities: ['Glacier Walk', 'Waterfall Tours', 'Northern Lights', 'Hiking'],
  },
  {
    id: 'new-york-city',
    name: 'New York City',
    country: 'USA',
    category: 'Urban',
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    description: 'The city that never sleeps with endless attractions',
    price: 2499,
    rating: 4.7,
    reviews: 4567,
    duration: '4 days',
    activities: ['Broadway Show', 'Museum Tour', 'Shopping', 'Food Tour'],
  },
  {
    id: 'dubai-luxury',
    name: 'Dubai',
    country: 'UAE',
    category: 'Luxury',
    image: 'https://images.unsplash.com/photo-1512453316034-9128c8d9f1c4?w=800&q=80',
    description: 'Desert dunes, modern skyscrapers, and luxury shopping',
    price: 2899,
    rating: 4.7,
    reviews: 3234,
    duration: '4 days',
    activities: ['Desert Safari', 'Burj Khalifa', 'Shopping', 'Beach'],
  },
  {
    id: 'thailand-adventure',
    name: 'Thailand',
    country: 'Thailand',
    category: 'Adventure',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    description: 'Temples, beaches, vibrant nightlife, and street food',
    price: 1599,
    rating: 4.8,
    reviews: 3456,
    duration: '5 days',
    activities: ['Temple Tours', 'Muay Thai', 'Beach', 'Night Market'],
  },
  {
    id: 'switzerland-alps',
    name: 'Switzerland',
    country: 'Switzerland',
    category: 'Mountains',
    image: 'https://images.unsplash.com/photo-1531366936337-7bc3a1541663?w=800&q=80',
    description: 'Alpine mountains, charming villages, and scenic trains',
    price: 3599,
    rating: 4.9,
    reviews: 2109,
    duration: '5 days',
    activities: ['Mountain Biking', 'Scenic Train', 'Hiking', 'Swiss Cuisine'],
  },
  {
    id: 'greece-islands',
    name: 'Greek Islands',
    country: 'Greece',
    category: 'Island Paradise',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?w=800&q=80',
    description: 'Whitewashed villages, azure waters, and Mediterranean culture',
    price: 2699,
    rating: 4.8,
    reviews: 2987,
    duration: '6 days',
    activities: ['Island Hopping', 'Beach', 'Sunset Views', 'Greek Food'],
  },
];
